### ISSUE TITLE
Javascript Examples

### ISSUE THREAD

**Issue by arsen3d** [gcash/bchd#300]
Example code does not work on newer version of node
my version: v10.2.1
required version: Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
https://github.com/gcash/bchd/tree/master/bchrpc/documentation/client-usage-examples/nodejs-grpc
```
arsen@imac5k2015 Downloads % git clone https://github.com/gcash/bchd.git
Cloning into 'bchd'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 20650 (delta 46), reused 49 (delta 22), pack-reused 20510
Receiving objects: 100% (20650/20650), 16.67 MiB | 7.87 MiB/s, done.
Resolving deltas: 100% (15104/15104), done.
arsen@imac5k2015 Downloads % cd bchd/bchrpc/documentation/client-usage-examples/nodejs-grpc/
arsen@imac5k2015 nodejs-grpc % node grpc.js
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '@grpc/grpc-js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/arsen/Downloads/bchd/bchrpc/documentation/client-usage-examples/nodejs-grpc/grpc.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
arsen@imac5k2015 nodejs-grpc % npm install @grpc/grpc-js 
npm WARN qrcode.react@0.6.1 requires a peer of react@0.12 - 0.14 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-update@15.3.0 requires a peer of react@^15.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-css-themr@1.7.1 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-mounter@1.2.0 requires a peer of react@0.14.x || 15.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-router@2.6.1 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-toolbox@1.1.2 requires a peer of react@^0.14 || ^15.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-toolbox@1.1.2 requires a peer of react-addons-css-transition-group@^0.14.0 || ^15.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN arsen No repository field.
npm WARN arsen No license field.

+ @grpc/grpc-js@0.6.10
added 2 packages from 1 contributor and removed 11 packages in 5.549s
arsen@imac5k2015 nodejs-grpc % npm install @grpc/proto-loader

> protobufjs@6.8.8 postinstall /Users/arsen/node_modules/protobufjs
> node scripts/postinstall

npm WARN qrcode.react@0.6.1 requires a peer of react@0.12 - 0.14 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-update@15.3.0 requires a peer of react@^15.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-css-themr@1.7.1 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-mounter@1.2.0 requires a peer of react@0.14.x || 15.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-router@2.6.1 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-toolbox@1.1.2 requires a peer of react@^0.14 || ^15.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-toolbox@1.1.2 requires a peer of react-addons-css-transition-group@^0.14.0 || ^15.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN arsen No repository field.
npm WARN arsen No license field.

+ @grpc/proto-loader@0.5.3
added 16 packages from 44 contributors and removed 11 packages in 6.124s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.11.3 → 6.13.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.0   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

arsen@imac5k2015 nodejs-grpc % ls
README.md	grpc.js
arsen@imac5k2015 nodejs-grpc % wget https://raw.githubusercontent.com/gcash/bchd/master/bchrpc/bchrpc.proto
--2019-11-05 20:50:21--  https://raw.githubusercontent.com/gcash/bchd/master/bchrpc/bchrpc.proto
Resolving raw.githubusercontent.com... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3305 (3.2K) [text/plain]
Saving to: 'bchrpc.proto'

bchrpc.proto                                         100%[====================================================================================================================>]   3.23K  --.-KB/s    in 0s      

2019-11-05 20:50:22 (19.9 MB/s) - 'bchrpc.proto' saved [14146]

arsen@imac5k2015 nodejs-grpc % ls
README.md	bchrpc.proto	grpc.js
arsen@imac5k2015 nodejs-grpc % node grpc.js                                                                
/Users/arsen/node_modules/@grpc/grpc-js/build/src/index.js:47
    throw new Error(`@grpc/grpc-js only works on Node ${supportedNodeVersions}`);
    ^

Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
    at Object.<anonymous> (/Users/arsen/node_modules/@grpc/grpc-js/build/src/index.js:47:11)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/arsen/Downloads/bchd/bchrpc/documentation/client-usage-examples/nodejs-grpc/grpc.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
arsen@imac5k2015 nodejs-grpc % node --version
v10.2.1
arsen@imac5k2015 nodejs-grpc % ls
README.md	bchrpc.proto	grpc.js
arsen@imac5k2015 nodejs-grpc % 
```

**Comment by zquestz** [comment]
The error appears to state that 10.10.0 is supported. Which is newer than what you are running.
